package uz.event.entity;

public enum State {
    MAIN_USER,
    MAIN_ADMIN,
    ADD_EVENT_NAME,
    ADD_EVENT_PRICE,
    ADD_EVENT_DESC,
    ADD_EVENT_CAPACITY,
    ADD_EVENT_DATE,
    EDIT_EVENT_ID,
    EDIT_EVENT_FIELD,
    DELETE_EVENT,
    MONEY,
    EDIT_EVENT_NAME,
    EDIT_EVENT_PRICE,
    EDIT_EVENT_DESC,
    EDIT_EVENT_CAPACITY,
    EDIT_EVENT_DATE
}
